version: '3.7'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file: [./.env]
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    networks:
      - shalust-network
      - default
  front:
    build: .
    dockerfile: Dockerfile.front
    ports:
      - "3000:3000"
    env_file: [./.env]
    volumes:
      - ./:/app
    working_dir: /app
    tty: true 
    command: yarn start
    networks:
      - shalust-network
      - default

networks:
  shalust-network:
    external: true
    name: shalust-network 
